name: Refresh
on:
  # performed every two hours
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

env:
  # time zone
  TZ: Asia/Shanghai

  # the url to the list of airports that you maintain yourself
  # each line include domain, coupon and invitation code, the domain must be included, and the latter two items are optional
  #CUSTOMIZE_LINK: ${{ secrets.CUSTOMIZE_LINK }}

  # include special protocols, such as vless hysteria2 and hysteria
  ENABLE_SPECIAL_PROTOCOLS: true

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Prepare
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"
          cache: "pip"

      - name: Install
        run: pip3 install -r requirements.txt

      - name: Refresh
        run: python -u subscribe/collect.py  --overwrite

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data
          git commit -m "Update data folder"
          git push

      - name: Timestamp
        run: date
